version: '3.4'

networks:
  devpoint.network:
    driver: bridge

services:
  devpoint.frontend:
    container_name: devpoint.frontend
    image: ${DOCKER_REGISTRY-}devpoint.frontend:latest
    depends_on:
      - "devpoint.api"
    build:
      context: ./App
      dockerfile: Dockerfile
    ports:
      - "4200:4200"

  devpoint.api:
    container_name: devpoint.api
    image: ${DOCKER_REGISTRY-}devpoint.api:latest
    depends_on:
      - "devpoint.db"
      - "gateway"
    build:
      context: .
      dockerfile: Web.API/Dockerfile
    ports:
      - "8001:80"
    environment:
      DB_CONNECTION_STRING: "host=devpoint.db;port=5432;database=devpoint_db;username=postgres;password=postgres"
    networks:
      - devpoint.network
  
  devpoint.db:
    container_name: devpoint.db
    image: postgres:latest
    ports:
      - "5432"
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "devpoint_db"
    networks:
      - devpoint.network

  gateway:
    container_name: gateway
    image: ${DOCKER_REGISTRY-}gateway:latest
    build:
      context: .
      dockerfile: Gateway/Dockerfile
    ports:
      - "8000:80"
    networks:
      - devpoint.network
    
volumes:
  db_volume: